---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.10.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# A refresher on logarithms

```{python tags=c("hide-cell")}
import numpy as np
# Don't use exponential notation in showing values in arrays.
# Only show array values to 4 decimal digits
np.set_printoptions(suppress=True, precision=4)
```

This is a whirlwind tour of logarithms.


## Logarithms calculate exponents


Logarithms ask the question of a number - "what exponent do I need in order to
make that number"?

The [exponent](https://en.wikipedia.org/wiki/Exponentiation) is the
superscript number when we take one number to the power of another.  For
example, we can read $10^3$ as "10 raised to the power of 3". The 10 in this
expression is called the *base*, and the 3 is the *exponent*.

In Python, we write that expression as:

```{python}
# 10 raised to the power of 3.  3 is the exponent.
10 ** 3
```

For example, consider the number:

```{python}
x = 100
```

I want to write that number as 10 raised to the power of something - $10^y$.
$y$ is the *exponent* that I need for 10, to make 100.  In this case I can see
that $y$ must be 2, because $10^2 = 10 * 10 = 100$.  If $x = 1000$ then $y =
3$ because $10^3 = 10 * 10 * 10 = 1000$. The function `np.log10` works this
out for us.  It takes the numbers we send it, and works out the exponent(s) it
needs to apply to 10 (the *base*), into order to get the input numbers.  For
example:

```{python}
np.log10([100, 1000])
```

The exponents don't have to be whole numbers.  For example, I can calculate
$10^{3.5}$:

```{python}
v = 10 ** 3.5
v
```

`np.log10` will find this exponent for me too:

```{python}
np.log10(v)
```

and:

```{python}
L = np.log10([100, 1000, v])
L
```

`np.log10` reverses the effect of calculating 10 to the power of some value.

```{python}
values = np.array([2, 3, 4])
v_exp_10 = 10 ** values
v_exp_10
```

```{python}
# log10 reverses the effect of 10 to the power of some values, to get those
# values back.
np.log10(v_exp_10)
```

Similarly, if I've transformed some values with `np.log10`, I can reverse that
transformation by taking 10 to the power of the transformed values:

```{python}
more_values = np.array([10, 15, 20])
v_log_10 = np.log10(more_values)
v_log_10
```

```{python}
# Taking 10 to the power of some values, reverses the effect of log10.
10 ** v_log_10
```

More on this below.

## Exponents less than, equal to 1

You may remember that exponents can be less than 1.  For example $10^{0.5}$ is
the square root of 10:

```{python}
print(np.sqrt(10))
print(10 ** 0.5)
```

Therefore:

```{python}
np.log10(np.sqrt(10))
```

It is a bit difficult to think about what $10^0$ might mean, but the rule is
that $10^0$ is equal to 1 (we will justify this rule towards the end of this notebook). 

Therefore log10 of 1 is 0 (as the log10 of 1 is asking 'what power would I have to raise 10 to in order to get 1?'):

```{python}
np.log10(1)
```

```{python}
10**0
```

Exponents can be negative.  A negative exponent gives the equivalent calculation to taking the power to the exponent without the minus sign, and then dividing into 1 - like this:

```{python}
print('10 ** -2 equals', 10 ** -2)
print('1 / 10 ** 2 equals', 1 / (10 ** 2))
```

Therefore, a log of a number less than 1 will be negative:

```{python}
np.log10([0.5, 0.1, 0.01])
```

But - logarithms don't know how to handle minus numbers.  For example, there is
no exponent you can apply to 10 to get -100:

```{python}
np.log10(-100)
```

## The logarithm base


So far all our examples of logs have been calculating the exponents for 10.
This is what `np.log10` does.  10 is called the *base* of the logarithm - the
number that we are calculating the exponent for. `np.log10` calculates
logarithms with base 10.

The base doesn't have to be 10.  Another common option is `np.log2` where we calculate the exponent we have to apply to 2, to get the input numbers:

```{python}
np.log2([2, 4, 8, 10])
```

In fact an even more common option is to use the special number $e$ as the
base.  This is because taking exponents or calculating logarithms with base $e$
have some very convenient mathematical properties, that are not relevant to us
here.  Log to the base e is so common that Numpy simply uses `np.log` to mean
logarithm to base $e$.

```{python}
print('e', np.e)
print('e squared', np.e ** 2)
print('e cubed', np.e ** 3)
```

As you would expect, `np.log` returns the exponent we need to apply to $e$ to recreate the input numbers:

```{python}
np.log([2.718281828459045, 7.3890560989306495, 20.085536923187664])
```

As for all log bases, log of 1 is 0, and numbers less than 1 give negative log
values:

```{python}
np.log([1, 0.5, 0.1])
```

Numpy has a function that calculates $e^y$ - `np.exp`.   It is just a short-hand for taking $e$ to the power of the input values.

```{python}
my_exponents = np.array([0, 2, 3, 0.5])
print("e raised to the power of the exponents", np.e ** my_exponents)
print("is the same as np.exp of the exponents", np.exp(my_exponents))
```

## Raising to the power and logs are inverses of each other

As you've already seen above, for base 10, the logarithm function is the
inverse (reverse operation) of raising numbers to the power of some base.

Let us return to base 10.  Consider `z = 10 ** y` and `np.log10(z)`.
`np.log10(z)` reverses the effect of the first step, taking 10 raised to the
power of `y`.  It returns the original `y` (maybe with some small loss of
precision).

```{python}
y = np.array([0, 0.5, 3, 6])
z = 10 ** y
print('Result (z) of raising 10 to the power of y', z)
w = np.log10(z)
print('Result of log10 on z restores original y', w)
```

This is true of any log base, but we have to remember to raise the numbers to the correct base.  Above, the base was 10, here the base is `np.e`.

```{python}
y = np.array([0, 0.5, 3, 6])
z_for_e = np.e ** y
print('Result (z_for_e) of raising e to the power of y', z_for_e)
w_for_e = np.log(z_for_e)
print('Result of log on z_for_e restores original y', w_for_e)
```

You've seen that `np.log10` is the inverse of raising 10 to the power of an
array.  In the same way, raising 10 to the power of an array reverses the effect of applying `np.log10`.

```{python}
a = np.array([0.5, 3, 5, 1])
b = np.log10(a)
print('Result (b) of log10 on a', b)
c = 10 ** b
print('Result of 10 raised to power b restores original a', c)
```

Here's the same thing with base `np.e`.

```{python}
a = np.array([0.5, 3, 5, 1])
b_for_e = np.log(a)
print('Result (b_for_e) of log10 on a', b_for_e)
c_for_e = np.e ** b_for_e
print('Result of 10 raised to power b_for_e restores original a', c_for_e)
```

## Multiplying is adding with logarithms

One very important property of logarithms is that, once we have transformed
values to logs, addition becomes equivalent to multiplication of the original
values.

This is easiest to see by example.  Here we multiply two numbers:

```{python}
y = 100 * 1000
y
```

We can do the same operation by:

* Taking the logarithm transform of the numbers.
* Adding the two logarithms.
* Inverting the logarithm transform by raising the result to the corresponding
  power.

We call this the log-add-unlog procedure.  Using this procedure, we replace
multiplication by addition of logs.

Let us see that in action:

```{python}
# log of input numbers.
v1 = np.log10(100)
v2 = np.log10(1000)
# add the logs
v3 = v1 + v2
# unlog by raising to the power of the result.
y_from_log = 10 ** v3
y_from_log
```

We can also do these operations on multiple values with arrays.

```{python}
# Standard multiplication.
arr = np.array([100, 1000])
# np.prod multiplies the elements of the array
print('Product of array', np.prod(arr))
```

Here's the log-add-unlog method on the array:


```{python}
# Log
log_arr = np.log10(arr)
log_arr
```

```{python}
# Add
log_sum = np.sum(log_arr)
```

```{python}
# Unlog.
print('log-add-unlog of array', 10 ** log_sum)
```

Why does this work?

Here is the mathematical notation for original multiplication:

$$
y = 100 * 1000
$$

We can also write this as:

$$
y = 10^2 * 10^3
$$

We can also write out the raised-to-the-power parts longhand, like this:

$$
y = (10 * 10) * (10 * 10 * 10)
$$

Dropping the brackets, that have no effect, we see that this is also equal to:

$$
y = 10^{2 + 3} = 10^5
$$

The rule we discovered here is that multiplying numbers expressed as 10 raised
to the power of exponents, gives 10 to the power of (the addition of the
exponents).

To take another example, you may remember that raising a number to the power of 0.5 is the same as the square root of that number.  So:

```{python}
print('10 raised to the power of 0.5', 10 ** 0.5)
print('is the same as sqrt 10', np.sqrt(10))
```

Now consider:

$$
y = 10^{0.5} * 10^{0.5}
$$

We can re-express this as:

$$
y = \sqrt{10} * \sqrt{10} = 10
$$

Again, the adding exponents rule works because:

$$
y = 10^{0.5} * 10^{0.5} = 10^{0.5 + 0.5} = 10^1 = 10
$$

You may now be able to see why the log-add-unlog trick works.  The log stage
extracts the exponents.  The addition is adding the exponents as above.  The
unlog stage in sticking the exponent back onto the original base number - in
our case, 10.

```{python}
arr = np.array([1, 10, 100, 1000, np.sqrt(10)])
print('Array:', arr)
print('Product of array:', np.prod(arr))
log_arr = np.log10(arr)
print('Corresponding exponents for 10:', log_arr)
log_sum = np.sum(log_arr)
print('Exponents added:', log_sum)
# unlog
print('Raised to the power of 10:', 10 ** log_sum)
```

You may also be able to see that the same log-add-unlog trick works for any log
base.  The exponents corresponding to each input number will differ for each
log base, and the unlog step needs to raise the power of the log base.

```{python}
print('Log-add-unlog for log base 2')
print('Array:', arr)
log2_arr = np.log2(arr)
print('Corresponding exponents for 2:', log2_arr)
log2_sum = np.sum(log2_arr)
print('Exponents added:', log2_sum)
# unlog
print('Raised to the power of 2:', 2 ** log2_sum)
```

Or base `np.e`:

```{python}
print('Log-add-unlog for log base e')
print('Array:', arr)
loge_arr = np.log(arr)
print('Corresponding exponents for np.e:', loge_arr)
loge_sum = np.sum(loge_arr)
print('Exponents added:', loge_sum)
# unlog
print('Raised to the power of np.e:', np.e ** loge_sum)
```

## More on negative exponents

Recall that we can think of positive exponents as shorthands for multiplication:

$
 10^2 = 10 * 10
$

This could also be written as:

$
10^2 = 1 * 10 * 10
$

The value of the exponent (in this case 2) tells us the number of times 1 gets multiplied by the base. This is why raising a base to the power of 1 always equals the base; because $10^1$ means 'multiply 1 by 10 once':

$
10^{1} = 1 * 10 = 10
$

We think of negative exponents in a similar way - as shorthands for division:

$
10^{-2} = 1 ÷ 10 ÷ 10
$

```{python}
10**-2
```

```{python}
(1/10)/10
```

The value of the negative exponent tells us how many times 1 gets divided by the base:

$
10^{-3} = 1 ÷ 10 ÷ 10 ÷ 10
$

```{python}
10**-3
```

```{python}
# 1 divided by 10 three times
((1/10)/10)/10
```

Put into words, a negative exponent $n$ means '1 divided by the base $n$ times'.

```{python}
print('10 to the minus 4 = ', 10**-4)
print('1 divided by 10 four times =',(((1/10)/10)/10)/10)
```

## Dividing is subtracting with logarithms

Once we have transformed two numbers to logs, if we subtract the logs, then this is the same as performing division on the original numbers.

Once again, this is easiest to see by example.  Here we divide two numbers:

```{python}
y = 1000/100
y
```

We can do the same operation by:

* Taking the logarithm transform of the numbers.
* Subtracting the two logarithms.
* Inverting the logarithm transform by raising the result to the corresponding
  power.

We call this the log-subtract-unlog procedure.  Using this procedure, we replace
division by subtraction of logs.

```{python}
# log of input numbers.
v1 = np.log10(100)
v2 = np.log10(1000)
# add the logs
v3 = v2 - v1
# unlog by raising to the power of the result.
y_from_log = 10 ** v3
y_from_log
```

We can do this same calculation just using exponents, and arrive at the same answer:

$$
y = 1000 ÷ 100
$$



```{python}
1000/100
```

We can also write this as:

$$
y = 10^3 ÷ 10^2
$$

```{python}
10**3/10**2
```

We can also write out the raised-to-the-power parts longhand, like this:

$$
y = 1 ÷ (10 ÷ 10 ÷ 10) ÷ (10 ÷ 10)
$$

```{python}
1/(10/10/10)/(10/10)
```

Dropping the brackets, that have no effect, we see that this is also equal to:

$$
y = 10^{3 - 2} = 10^1
$$


```{python}
10**(3-2)
```

```{python}
10**1
```

If we divide a number by itself, we get 1:

```{python}
100/100
```

Given that subtracting logs is the same as dividing the original numbers, this is the same as if we
subtract a logged number from itself, and then unlog the result:

```{python}
np.log(100) - np.log(100)
```

```{python}
# unlogging the value in the cell above
10**(np.log(100)-np.log(100))
```

This is the same as raising the number to the power of 0:

```{python}
v1**0
```

## Why does anything raised to the power of 0 equal 1? AKA why log(1) always equals 0

1 is the first element in the `arr` array which we used above. `np.log(arr)` transforms the first element into a 0. 

```{python}
print(arr)
np.log(arr)
```

The answer will be 0 whenever 1 is log-transformed, for instance in the first step of the log-add-unlog trick. Remember that the log of 1 is asking the question "what power would I have to raise the base to, in order to get 1?". 

```{python}
# the base 10 log of 1 (e.g. "what power would I have to raise 10 to, in order to get 1?")
np.log10(1) 
```

```{python}
# 10 to the power of 0

10**0 
```

As we mentioned earlier anything raised to the power of 0 equals 1. 

```{python}
print(2**0)
print(10**0)
print(1/800**0)
print(124638210**0)
```

This is the case because the way we calculate divisions like $10^4/10^2$ is by subtracting the bottom exponent from the top exponent e.g. $10^4/10^2 = 10^{4-2} = 10^2$. 

```{python}
10**4/10**2
```

```{python}
10**2
```

A consquence of this is that for divisions like $10^2/10^2$, we calculate $10^2/10^2 = 10^{2-2} = 10^0$. Since anything (in this case $10^2$) divided by itself must equal 1, this means that $10^0$ equals 1.

This means that the log of 1 (to any base) is 0:

```{python}
print(np.log(1))
print(np.log2(1))
print(np.log10(1))
```

Similarly, as we mentioned earlier, when we multiply two bases with exponents, we add the exponents, e.g.: $10^2 * 10^3 = 10^{2+3} = 10^5 = 100000$

```{python}
10**2 * 10**3
```

```{python}
10**5
```

If one of the exponents is 0, this means we add 0 to the other exponent: $10^2 * 10^0= 10^{2+0} = 10^2 = 100$

This is only possible if $10^0 = 1$.

```{python}
10**2 * 10**0
```

```{python}
10**2 * 1
```

This has the consequence that, if we multiply two bases with exponents of the same absolute magnitude, but opposite signs, the answer must be 1: $10^2 * 10^-2 = 10^{2-2} = 10^0 = 1$

This is only possible if the base with the negative exponent is the reciprocal of the base with the positive exponent (the reciprocal of a number is 1 divided by that number):

```{python}
10**2 * 10**-2
```

```{python}
10**2 * 1/10**2
```

In fact, for any number (represented as $n$):

$
\text{base}^{-n} == 1/\text{base}^{+n}
$

So for instance:

$
10^{-4} = 1/10^{4}
$


```{python}
10**-4
```

```{python}
1/10**4
```

```{python}

```
